### ISSUE TITLE
Can't compile outside of CordovaCameraPreviewApp

### ISSUE THREAD

**Issue by toots** [mbppower/CordovaCameraPreview#1]
The plugin code doesn't seem properly factored-out from the demo app. See for instance:

```
import com.mbppower.CordovaCameraPreviewApp.R;
```

in `CameraActivity.java`

**Comment by mbppower** [comment]
Thanks, fixed in master and in cordova plugin registry version 0.0.4
The sample app also has been updated.

**Comment by toots** [comment]
Awesome, thanks!
