### ISSUE TITLE
[Question] Image outputed as a Data URI?

### ISSUE THREAD

**Issue by iRuisu** [mbppower/CordovaCameraPreview#11]
Would you be able to add a Data URI output option? This plugin works perfectly for my project but I'm needing to save the photos as a data uri, could this be a possible feature that can be implemented?

Thanks for this awesome plugin none the less!

**Comment by bogomips** [comment]
I'd like a similar feature because I need to send the base64 through a webservice

**Comment by bogomips** [comment]
I thought it could be a good idea to use cordova-plugin-file plugin to read file and get base64

**Comment by mbppower** [comment]
Yes, you should use the cordova-file in order to read the picture file and them get the base64.
Please, refer to this documentation: http://docs.phonegap.com/en/edge/cordova_file_file.md.html

readAsDataURL: Read file and return data as a base64-encoded data URL.

**Comment by McGern** [comment]
Would you be able to add an example of using the file documentation please? (or point to a more recent version). I am trying to use the described example but can't work out how to load the file path in the filereader

**Comment by rphansen91** [comment]
In case anyone is having issues figuring out how to load the image as base64

Place this code inside of the setOnPictureTakenHandler callback

```
//LOAD THE FILE AS BASE64
var reader = new FileReader();
reader.onloadend = function (evt) {
      console.log(evt.target.result)
};
reader.onerror = function (evt) {
    send("CAMERAPREVIEW_ERROR");
};

//LOAD THE FILE FROM DISK
window.resolveLocalFileSystemURL(
            result[0], 
            function (fileEntry) {
                fileEntry.file(function (file) {
                    reader.readAsDataURL(file)
                })
            },
            function (err) {
            }
)
```

**Comment by erperejildo** [comment]
@rphansen91 Your code didn't work to me, reader.onloadend never trigger.
I tried as well with this:
```
readFile(fileEntry) { // picture
    fileEntry.file(function(file) {
      var reader = new FileReader();
      reader.onloadend = function() {
        console.log("Successful file read: " + this.result);
        displayFileData(fileEntry.fullPath + ": " + this.result);
      };
      reader.readAsText(file);
    }, that.onErrorReadFile);
  }
```
