### ISSUE TITLE
[Request] Camera in the background

### ISSUE THREAD

**Issue by JarvisHocka** [mbppower/CordovaCameraPreview#12]
Hello there,
I would like to know if it is possible to render the camera in the background. While the HTML still being rendered on top.
I am also willing to pay for this feature to be added as i need this for a project.
Jarvis

**Comment by errlogb** [comment]
Would like this feature too!

**Comment by adanreyes18** [comment]
I urge the camera feature of the bottom please get in touch with me : adan.reyes@synelmex.com

**Comment by rrNuvoPoint** [comment]
What is the purpose? You can just hide the "popup" and still interact with it like taking pictures.

**Comment by adanreyes18** [comment]
The purpose is to integrate this: https://software.intel.com/en-us/html5/articles/augmented-reality-mobile-app-with-html5 my app , show html content above the camera

**Comment by mbppower** [comment]
i gonna commit this feature today. For ios.

**Comment by adanreyes18** [comment]
And Android? Can You doing to Android too?

**Comment by mbppower** [comment]
Please, check for the new version. I've added the feature for both platforms.
Docs and sample app have been updated.
For that to work, the webview background should be transparent. The background of the app will be black, but you can put some transparent PNG using CSS on the background to solve the visual.
If you have a better idea, please tell me. ;)

**Comment by adanreyes18** [comment]
Thank you very much perfect, give me your mail for contact Greetings

**Comment by adanreyes18** [comment]
When compiling Intel XDK shows me an error that the java class : CameraActivity.java use or overrides a deprecated API. Do you know why ? you have skype to be in direct contact?
