### ISSUE TITLE
Return image content to JavaScript

### ISSUE THREAD

**Issue by jacobweber** [mbppower/CordovaCameraPreview#13]
I'd like to be able to get the image's content on the JavaScript side, instead of saving it to a file. Maybe it could be passed to the callback function as a base64-encoded string

This would let you pass it somewhere with an XMLHttpRequest, instead of saving it. And it would let you show it with a background-image property, e.g. with "data:image/png;base64,".

Thanks for the plugin, by the way...it's very helpful.

**Comment by mbppower** [comment]
Please, use the cordova-file in order to read the picture file and them get the base64.
Please, refer to this documentation: http://docs.phonegap.com/en/edge/cordova_file_file.md.html
Method readAsDataURL: Read file and return data as a base64-encoded data URL.

**Comment by jacobweber** [comment]
Fair enough, but it might be easier to have the option, so you don't have to deal with the saved files if you just want to use the images temporarily on the JS side. You mind if I submit a pull request?
