### ISSUE TITLE
iOS preview has black border on top and right

### ISSUE THREAD

**Issue by jacobweber** [mbppower/CordovaCameraPreview#14]
The camera view on iOS has a black bar on the top and right sides. Here's an example with the demo app, with an iPhone 6 running iOS 8.1.3:

![img_0671](https://cloud.githubusercontent.com/assets/542988/6087074/e1175658-adfb-11e4-9989-b09f1e871a8f.PNG)

**Comment by mbppower** [comment]
I'll try to look into this on the simulator. Thanks.

**Comment by jacobweber** [comment]
Sure. Let me know if you need help -- I don't think the simulator shows a camera.

**Comment by jacobweber** [comment]
It looks like this is because Display Zoom was on. When that's the case, the 2x scaling reported by [UIScreen scale] is wrong. This is used in CameraRenderController.m. Using nativeScale seems to work, although it's only supported in iOS 8. Maybe something like this?

```
CGFloat pointScale;
if ([[UIScreen mainScreen] respondsToSelector:@selector(nativeScale)]) {
    pointScale = [[UIScreen mainScreen] nativeScale];
} else {
    pointScale = [[UIScreen mainScreen] scale];
}
```
