### ISSUE TITLE
preview box changes dimension while taking pic

### ISSUE THREAD

**Issue by bogomips** [mbppower/CordovaCameraPreview#16]
Hello,
as I wrote in the title, while I take a picture and I see the black surface with loader, that surface changes dimension increasing the width.
Is it possible to prevent this behavior ?

Is it also possible to have a transparent surface instead of black (continuing to see the images) 

I had developed a similar plugin in the past but the js interface was not so good like this one,it would be amazing to me to have that features.

thanks

**Comment by mbppower** [comment]
Hello,

Yes I'll make the black background transparent (You can change it too, if you see the layout xml file). For the dimension changing I think it depends on the aspect ratio of the provided dimension. Could you please send me your configuration and device OS version?
Thanks

**Comment by bogomips** [comment]
Hi, actually it was pretty easy changing the alpha channel in camera_activity.xml :)
I'm also trying to understand what's going on about sizes and aspect ratio i mean,
what I noticed is that the live preview appears like zoomed and when I click to take the picture the aspect ratio changes (like squashed on vertical), the picture I get as file is not zoomed and I can see a bigger area than I can see during the (zoomed) preview.

I checked logcat and I found the supported resolutions:

D/CameraHal(  101): Support Preview sizes: 640x480,1280x720,960x544,800x448,640x360,424x240,352x288,320x240,800x600,176x144,160x120,1280x800 
D/CameraHal(  101): Support Picture sizes: 640x480,1280x720,960x544,800x448,640x360,424x240,352x288,320x240,800x600,176x144,160x120,1280x800 

So I tested using  one of those resolutions, same issue.
With a vertical rect:
cordova.plugins.camerapreview.startCamera({x: 30, y: 32, width: 800, height:1280}, "front", tapEnabled, dragEnabled); 

Even with an orizontal rect
cordova.plugins.camerapreview.startCamera({x: 30, y: 32, width: 1200, height:800}, "front", tapEnabled, dragEnabled);  


I'd even like to add a countdown so i'm wondering if is possible add an html layer
over the preview surface.

I'm using  Microsoft LifeCam HD-5000 as camera
Istick A200 with android 4.1.1 onboard
orientation vertical (portrait)

Thanks

**Comment by bogomips** [comment]
Hi,
about the issue that i describe above is probably related to non squared frame sizes.
 
I setted in the js 1080x1600 as surface, these lines make it a square of 1600x1600 and that square is just what i get while i take the picture (this is why it become larger)
unfortunately I didn't have time to go deeper in the issue.

int size = Math.max(frameContainerLayout.getHeight(), frameContainerLayout.getWidth());                  
FrameLayout.LayoutParams camViewLayout = new FrameLayout.LayoutParams(size, size);

About the countdown I had to hardcode something in a not elegant way just to delivery in time my project.
Anyway i think would be quite easy to integrate this function in a better way and customizable from js.
So I write down the lines of code i wrote to do it,  maybe can make the implementation faster:

Inside the relativeLayout i had this xml

<TextView
android:id="@+id/countnum"
android:layout_width="fill_parent"
android:layout_height="match_parent"
android:gravity="center"
android:text=""
android:textColor="#8FFF"
android:textSize="300sp" />


In cameraActivity.java

import android.widget.TextView;
import android.os.CountDownTimer;

I modified the mothod takePicture()

final TextView vistaTesto = (TextView) view.findViewById(getResources().getIdentifier("countnum", "id", appResourcesPackage));

	new CountDownTimer(6000, 1000)  {
		private int count=5;
		public void onTick(long millisUntilFinished) {
				if (count==1) {
					vistaTesto.setText(count + " :-)");
				}
				else {            		        				         			            		       
					vistaTesto.setText("" + count);
				}
				count--;
			}

			public void onFinish() {	        
				
				vistaTesto.setText("");
                         public void onPreviewFrame(final byte[] data, final Camera camera) { 
                              [...]

		}
			}.start();

**Comment by mbppower** [comment]
Hi.. now it's possible to add the preview at the back of the webview. Please see the last release.
I think that there are more issues with the frame aspect ratio on Android, unfortunately I haven't had much time to spend on this project yet.
