### ISSUE TITLE
Unsupported Plugin in Phonegap Build !

### ISSUE THREAD

**Issue by Ekta09** [mbppower/CordovaCameraPreview#18]
I am developing an application in cordova/phonegap with DevExtreme. I am used to add plugins in my application via Online Phonegap Build. But when I am using this plugin : add <gap:plugin name="com.mbppower.camerapreview"/> Error pop ups: Unsupported Plugin !!

If it is unsupported in that , how can I add in my application to access CamerePreview mode ? (I can't use CLI) @mbppower ,  or anyone please help me out. Thanks a lot in advance.

**Comment by bau720123** [comment]
hi @Ekta09 
when in PGB is like that
```
<gap:plugin name="com.mbppower.camerapreview" version="0.0.8" source="plugins.cordova.io" />
```

**Comment by Ekta09** [comment]
Ohh yes its working I didn't know which source should be taken. Wow thanks a ton. :+1:

**Comment by mbppower** [comment]
I'll add this to the docs
