### ISSUE TITLE
In landscape, Android preview is in the wrong place

### ISSUE THREAD

**Issue by jacobweber** [mbppower/CordovaCameraPreview#23]
If I rotate an Android phone to landscape mode, and open a camera view with a width larger than 500px or so, the left and right sides of the camera view appear in the wrong places. They snap back into place when you call takePicture.

You can reproduce this on the Preview app:
* Change the onStartCamera function in index.js to pass the following size element:
`{x: 0, y: 100, width: 560, height:300}`
* Add an element of the same size for reference, to index.html just after the `<body>` start tag:
`<div style="position:absolute; border: 1px solid red; left: 0px; top: 100px; overflow: hidden; width: 560px; height: 300px;"></div>`
* Rotate the device to landscape.
* Tap Start Camera.
* The preview appears like this:
![screen](https://cloud.githubusercontent.com/assets/542988/6742768/d3a781fe-ce4f-11e4-9e89-bdb1a3ca4bca.png)
* If you replace 560 with 300 in the above values, the preview appears with the right size.

Tested on a Nexus 5 with Android 5.0.1.

**Comment by jacobweber** [comment]
It looks like it might be briefly appearing in the right position, before being resized. In the logs I see this:
```
D/Preview (17396): previewWidth:1280 previewHeight:720
D/layout  (17396): left:0
D/layout  (17396): top:72
D/layout  (17396): right:1344
D/layout  (17396): bottom:828
```
and then later:
```
D/layout  (17396): left:200
D/layout  (17396): top:0
D/layout  (17396): right:1480
D/layout  (17396): bottom:960
```

**Comment by Ekta09** [comment]
Yeah Great work. It is working for android, can you please do same thing for iOS also ? Thank you so much for this classic plugin. :)

**Comment by erperejildo** [comment]
Portrait still having the same problem
