### ISSUE TITLE
iOS: maxWidth / maxHeight intrepreted as minimal values

### ISSUE THREAD

**Issue by squio** [mbppower/CordovaCameraPreview#27]
Not completely sure this is a bug or rather my interpretation.

I take a picture with the following parameters: `takePicture({maxWidth:640, maxHeight:640});`
Expected result: the saved image will be at most 640 pixels width OR height, the other dimension smaller.
Actual result: the smallest dimension is 640 pixels, the other dimension bigger.
If this is not intended the fix is trivial: change the less than comparison into greater than in line 202 of `CameraPreview.m` like this:

				CGFloat scale = scaleHeight > scaleWidth ? scaleWidth : scaleHeight;

**Comment by mbppower** [comment]
I haven't had much time to spend on this project. Your help is very appreciated. Thanks.
