### ISSUE TITLE
feature request of multiple images taken at once

### ISSUE THREAD

**Issue by rrNuvoPoint** [mbppower/CordovaCameraPreview#28]
I am working on a school project were we want to do a photosession of 20 images, analyse them, delete them and then take 20 more if the first ones are not bad. We want to create a 2D FFT on the images. would it be possible to capture 20 frames in a row (within 2 seconds)?

**Comment by mbppower** [comment]
Your project sounds interesting. For that to work you should capture a video, which almost all middle-end to high-end phones can capture at 24 frames per second. Some high-end phones can take several pictures very fast. I'd stick with the video approach as it is more easy and phone agnostic. After you manage to capture the video, you should split its frames, them you can get separate pictures.

Unfortunately, this plugin can't capture video out-of-the-box. But it's possible to change the code, and get separate images from the video output.

iOS - CameraRenderController.m : line 130
Android - CameraActivity.java : line 327

You have to do a foreach and save you images..

**Comment by rrNuvoPoint** [comment]
I would tak a look. Thank you for you quick response!
