### ISSUE TITLE
Black screen on IOS 8.1.2 Ipad

### ISSUE THREAD

**Issue by ArecaDesign** [mbppower/CordovaCameraPreview#4]
When the plugin for Cordova Camera Preview is ran on IOS 8.1.2. The app will load up fine, but when the start camera function is called. The screen goes black with the camera view displayed on the screen. Please see the screenshot below.

![img_0117](https://cloud.githubusercontent.com/assets/10530226/5738337/13954afc-9be3-11e4-8486-40d216822589.PNG)

Any idea why this is? I have used the application demo and still get the same bug.

**Comment by mbppower** [comment]
Thanks. For the iOS 8 Apple has changed some things for presenting transparent modal view controllers. The plugin and preview app has been updated. Please test in your device again.
