### ISSUE TITLE
can not fine symbol : method setBackgroundColor(int)

### ISSUE THREAD

**Issue by dhirenipatel** [mbppower/CordovaCameraPreview#40]
Cordova Version: 5
Java Version : 1.8

CameraPreview.java:107: error: cannot find symbol webView.setBackgroundColor(0x00000000);
						       
  symbol:   method setBackgroundColor(int)
  location: variable webView of type CordovaWebView

CameraPreview.java:108: error: cannot find symbol ViewGroup g = (ViewGroup)webView.getParent();
						                                
  symbol:   method getParent()
  location: variable webView of type CordovaWebView
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

**Comment by mbppower** [comment]
That seems to be a problem with Cordova version 5. I'll need to see the API changes and correct that issue.

**Comment by dhirenipatel** [comment]
I changed code to 
webView.getView().setBackgroundResource(0x00000000);
ViewGroup g = (ViewGroup)webView.getView().getParent();

but not helping much. Error got removed but camera is not going to background like before

**Comment by io-pan** [comment]
I have the same issue: cordova 5.0.0, building app for android 4.4.2 (API 19)

All is ok except sending camera to back, I get these errors:
method getParent() is undefined for the type CordovaWebView
method setBackgroundColor(int) is undefined for the type CordovaWebView

I've tried to cast types but this doesn't work either.

I managed once to make it work by orverwriting files with the CordovaCameraPreviewApp files. But as soon I closed eclipse and re-open my project, these 2 errors came back.

**Comment by marcorivm** [comment]
Any news  on this? also facing this problem

**Comment by ReneMoraales** [comment]
+1, any news regarding this issue?

**Comment by io-pan** [comment]
@mbppower : what version number of cordova are you using ?

**Comment by mbppower** [comment]
They've changed some things on the version 5. I was using Cordova 4.

**Comment by SeanChenU** [comment]
One of the workarounds is commenting out the part that causes error.... at least I can use some of the features of this plugin

**Comment by SeanChenU** [comment]
Finally found a possible solution for this issue. Change the code 
```
webView.setBackgroundColor(0x00000000);
ViewGroup g = (ViewGroup)webView.this.getParent();
g.setBackgroundColor(0x00000000);
g.bringToFront();
```
to 

```
webView.getView().setBackgroundColor(0x00000000);
((ViewGroup)webView.getView()).bringToFront();
```

The class CordovaWebView in Cordova 5 is no longer inherited from WebView class in android. So the getParent() and setBackgroundColor() don't work. The down side of sending the camera preview box to the back of the webView is you can't drag the preview box.

**Comment by io-pan** [comment]
Well done SeanChenU.
    this works perfectly for me.
