### ISSUE TITLE
Android camera preview not showing on first app load

### ISSUE THREAD

**Issue by joshuaohana** [mbppower/CordovaCameraPreview#45]
I open up the app and the camera preview window is not shown. If I simply minimize the app then open it again it's there like magic! I added an alert which is fired on camera.show, for some reason this does not actually happen until the second open. Any idea why?

**Comment by proxsys** [comment]
I had the same issue but it was caused by the device not being ready and probably cordova too.

I made sure the camera start would be first instantiated when the device was ready and this fixed the issue.

Hope this helps and that it isn't over obvious.

Thanks!

**Comment by joshuaohana** [comment]
Thanks I ended up solving it in a similar way and forgot to reply. I was hiding on launch then showing when they reached a secondary page, I had to wrap that initial hide in a timeout and it fixed the problem.
