### ISSUE TITLE
Disable save to camera roll and just return a data URI

### ISSUE THREAD

**Issue by awoodall** [mbppower/CordovaCameraPreview#50]
For my project I use Firebase to store my images as Data URI's. It would be great to disable save to camera roll and just return a data URI string.

**Comment by developeron29** [comment]
+1

**Comment by Jimbo13M** [comment]
Hi,

I had the same needs for one of my projects.
I've made this <a href="https://github.com/Jimbo13M/CordovaCameraPreviewBase64">little modification</a> on the cordova plugin that stops saving on camera roll and returns the photo as a base64 jpg url.

BR

**Comment by DBZFYAM** [comment]
@Jimbo13M, does your modification still work with the current version? I also need the base64 version of the photo but after replacing the file, I still get the same output from setOnPictureTakenHandler:

["assets-library://asset/asset.JPG?id=23569151-278F-469B-98B2-583A8BF839E5&ext=JPG", "assets-library://asset/asset.JPG?id=74749DFD-E078-4E35-976A-47C7DEE13920&ext=JPG"] (2)

Also, in your example, this line is used:
b64url.replace('file:///','')

However, the result I get starts with assets-library:// and isn't Base64 encoded. Help would be greatly appreciated!
