### ISSUE TITLE
Can not install plugin with cordova

### ISSUE THREAD

**Issue by steven274** [mbppower/CordovaCameraPreview#52]
When I run command
cordova plugin add https://github.com/mbppower/CordovaCameraPreview.git

it shows an error :
Error: EXDEV, cross-device link not permitted

How to fix that, thanks

**Comment by ricardokrieg** [comment]
Check this: http://stackoverflow.com/questions/30801307/upgrade-cordova-cannot-install-plugins-from-git-urls-anymore

cloning the repo and installing from local path worked for me.

```
git clone https://github.com/mbppower/CordovaCameraPreview.git some/path/here
cordova plugin add some/path/here
```
